version: "3.8"

networks:
  default:
    driver: bridge

services:
  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=#dadospro3131
 